### ISSUE TITLE
Call to undefined method Illuminate\Database\Schema\Blueprint::id()  

### ISSUE THREAD

**Issue by sangnguyenplus** [TheOrchid/Platform#244]
Hi TheOrchid team,
I got this error when try to install.

```
Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Database\Schema\Blueprint::id()  
```
`$table->id` should be change to `$table->integer` or you're missing some dependencies so it can't work now.

Thanks!

**Comment by tabuna** [comment]
Hi sangnguyenplus, thanks for the feedback, I will fix this soon
