### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by d8vjork** [TheOrchid/Platform#251]
Hi, Yesterday I discover that fantastic project (congrats for your progress with it).

I'm trying to create a user with artisan command:
`php artisan make:admin nickname email@email.com secretpassword`

And on installation, but it says User already exists! (artisan command), and the installation doesn't create any user.

I'm working local on Windows 10 with PHP-FPM, IIS (but I try with php serve command). So I will contribute with this project.

**Comment by tabuna** [comment]
Hi, can you say more information
What software do you use? And what version? (PHP, Laravel, MySQL or PostgreSQL)

**Comment by d8vjork** [comment]
Yes, Laravel 5.4 (last version, fresh installation), PHP 7.1.2, MariaDB 10.1.21

**Comment by tabuna** [comment]
JSON format [support MariaDB 10.2 ](https://mariadb.com/resources/blog/json-mariadb-102)

**Comment by d8vjork** [comment]
Ok, so you have json in migrations.

Thanks, I try upgrading MariaDB 👍

**Comment by d8vjork** [comment]
Ok, sorry, but still can't because migrations of Orchid doesn't migrate (the user schema that I can see in my database is the user from Laravel fresh installation).

**Comment by tabuna** [comment]
You made
`php artisan vendor:publish` &
`php artisan migrate` ?
At these stages there were no problems?

**Comment by d8vjork** [comment]
Yes, I change the query exception for make:admin command and this is the result:

https://gist.github.com/d8vjork/71264a2f0b909ac17c16ec0379662602

The solution: I change the json/jsonb to text from some migration files and run `php artisan migrate` (and yes, I upgrade MariaDB to 10.2 but it continues having problems with JSON from Laravel).

**Comment by tabuna** [comment]
But he also clearly says that not all migrations have passed.
I need some time to reproduce the problem on MariaDB

**Comment by tabuna** [comment]
I was able to reproduce the problem and get an error.
But, as it turned out the JSON type is still not supported in MariaDB.

[Link 1](https://laracasts.com/discuss/channels/eloquent/table-json-generates-an-error-when-running-migrations?page=1)
[Link 2](https://stackoverflow.com/questions/42425667/mariadb-json-support-in-laravel)
[Link 3](https://github.com/laravel/framework/issues/13622)

**Comment by d8vjork** [comment]
So, this only support MariaDB 10.3 (alpha) / MySQL 5.7 and future versions of both.
