### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by AnisBoss** [TheOrchid/Platform#255]
Hello , 

First Thanks for the Platform , 
After following [the installation guide ](https://theorchid.github.io/docs/installation/) i note that two tables added to the database chosen _users_ and _migrations_ .
But after the graphical installation step , there is no line added to the DB 
and when i try to login , this process failed with **These credentials do not match our records.**
any help ?
Thanks .

**Comment by powolnymarcel** [comment]
Same problem here

**Comment by AnisBoss** [comment]
Hello , 
After doing some research , i found the issue source : 
Migration is failed due to key error (key is too long than 1000 bytes ) 
so to fix this  : 
add to the boot function in _app/Providers/AppServiceProvider.php_ 
`Schema::defaultStringLength(191);`
don't foget to  include the necessary use statement at the top of the file: 
`use Illuminate\Support\Facades\Schema;`
Hope this helps solving the issue .

**Comment by tabuna** [comment]
Hello, please check if all migrations have been installed, if not, run artisan vendor: publish & artisan migrate. After that, you can also create a user using the artisan make: admin command.
Also, please specify that your database (MySQL v 5.7 or PostgreSQL) must support JSON.

I have encountered such cases if the graphical installer was started using artisan serve. It does not have the ability to update .env in the process.
