### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by imMMX** [TheOrchid/Platform#264]
Hi,

  when ive done everything follow the documention,i still cant login after installation.

  the webpage show me the message "These credentials do not match our records."

  and there is no any records in Users table in the database.

  can u help me

**Comment by imMMX** [comment]
i figured it out.

cause migration failed.

how to resolve:

step 1. edit your AppServiceProviders.php

  add `use Illuminate\Support\Facades\Schema;`

  edit function boot

  add `Schema::defaultStringLength(191);`

step 2.  edit `2016_02_09_194940_create_post_table.php`

  edit `$table->string('slug','255')->unique();` to `$table->string('slug')->unique();`

  length 255 will cause 767bytes limited error.MariaDB and MysqlDB length is 767.

step 3.  edit all migration files if contain json type.

  if your mysql version < 5.7.8 ,it does not know what json type it is.

  change it like  `$table->json('permissions');` -> `$table->text('permissions');`

done.

**Comment by tabuna** [comment]
Hello, I know about such a problem.
This was described in #255 and #251 .
```
$users = DB::table('users')
                ->where('options->language', 'en')
                ->get();

$users = DB::table('users')
                ->where('preferences->dining->meal', 'salad')
                ->get();
```
I'm [using the possibilities](https://laravel.com/docs/5.4/queries#json-where-clauses) that json gives and I can hardly give it up.

**Comment by tabuna** [comment]
It is possible for such cases to write at the installation stage, that you need to update the database
