### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by SmoDav** [TheOrchid/Platform#266]
Hi,
I was wondering if you are okay with the change of the namespaces as your composer.json has so many declarations. Would you mind it being changed to src/Orchid as the Orchid namespace and also a combined helpers file? Would like to contribute but want to know if modifying the structure is actually something you would like.

**Comment by tabuna** [comment]
Hi, do I understand correctly that you want to move the app to src/ with the name Orchid?

**Comment by SmoDav** [comment]
Idearly, I would want to move everything under app and source to src/Orchid then have the namespace route of Orchid to src/Orchid. See sample
![sample](https://user-images.githubusercontent.com/2639600/27348536-140723a8-55fd-11e7-9fbf-ad79f7df3a15.png)

**Comment by tabuna** [comment]
I have nothing against this decision. And I will accept your PR.
Can you explain why you want such a solution?

**Comment by SmoDav** [comment]
My main concern is how large the psr-4 autoload will grow since the current composer file autoloads so many namespaces which are from a common root ```src``` and one that is from a different route ```app```
Having a common route will allow for better growth and addition of countless namespaces under the root ```Orchid```

**Comment by tabuna** [comment]
It may make sense to take part  src/ in separate packages?
Because for example Widget / Access / Alert/ Widget ... Can be used without Orchids.

**Comment by SmoDav** [comment]
We can remove the independent packages from the cms then require them accordingly within the main Orchids repo. They will still end up residing within the same directory in the long run. Why don't we first start by making the packages independent of Orchids since they are already 99% independent, then require them when installing Orchids so that it installs Orchids and the dependencies. Like create orchids/alert, orchids/access then require them in Orchids cms

**Comment by tabuna** [comment]
I do not know what to do in this situation, but let's try.
It will take me some time to render all independent packages separately

**Comment by SmoDav** [comment]
Please make a repository for the main packages e.g. Alert, Widget... To migrate them will take a very short time. I will handle the migration.

**Comment by tabuna** [comment]
You expected such behavior?
