### ISSUE TITLE
Possible bug with locales and Many Behaviour

### ISSUE THREAD

**Issue by angay9** [TheOrchid/Platform#267]
I have been exploring the package. I am trying to create management for employees, so I basically have the Employee behavior that extends HasMany behavior.
```php
<?php namespace App\Core\Behaviors\Many;

use Orchid\Behaviors\Many;
use Orchid\Http\Forms\Posts\BasePostForm;
use Orchid\Http\Forms\Posts\UploadPostForm;

class Employee extends Many
{

    /**
     * @var string
     */
    public $name = 'Employees';

    /**
     * @var string
     */
    public $description = 'Employees';

    /**
     * @var string
     */
    public $slug = 'employees';

    /**
     * @var string
     */
    public $icon = '';

    /**
     * Slug url /employee/{name}.
     * @var string
     */
    public $slugFields = 'name';

    // public $model = \App\Employee::class;

    /**
     * Rules Validation.
     * @return array
     */
    public function rules() : array
    {
        return [
            'id'    =>  'sometimes|integer|unique:posts',
            'content.*.name'  =>  'required|string',
            'content.*.birth_date'   =>  'date'
        ];
    }

    /**
     * @return array
     */
    public function fields() : array
    {
        return [
            'name'        =>   'tag:input|type:text|name:name|max:255|required|title:Employee name|help:Employee name',
            'birth_date'        =>    'tag:datetime|type:text|name:open|max:255|title:Birth date|help:Birth date',
        ];
    }

    /**
     * Grid View for post type.
     */
    public function grid() : array
    {
        return [
            'name' => 'Name',
            'birth_date' => 'Birth day'
        ];
    }

    /**
     * @return array
     */
    public function modules() : array
    {
        return [
            // BasePostForm::class,
            UploadPostForm::class
        ];
    }
}
```
As you can see I have the BasePostForm commented out in the modules function. If I create a new entry and try to edit it no edit form is displayed. I have explored the code and the problem is that when I don't have the BasePostForm nothing is being stored in the options column inside the posts table, but it probably would have to store some sort of json like this:
```js
{"locale": {"en": "true", "pl": "true"}}

```
but since the column is empty no form is being shown on the edit page of the employee.
I am not sure if it is an expected behavior or it's a bug. My proposal would be that if the BasePostForm is not present then the default value should be stored inside the options column. That would probably fix the issue.
Thanks

**Comment by tabuna** [comment]
Yes, you are right, the language settings should be present by default when creating an entry, I will issue a patch to fix this within an hour

**Comment by tabuna** [comment]
I did the expected behavior, if there are problems write
