### ISSUE TITLE
Passing attributes as an array

### ISSUE THREAD

**Issue by tabuna** [TheOrchid/Platform#269]
I think it's worth supporting both types of entries, since the line view does not allow the declaration of lists (associative), tables or functions of closures

**Current view:**
```php
/**
* @return array
*/
public function fields() : array
{
    return [
        'body'        => 'tag:wysiwyg|name:body|max:255|required|rows:10',
    ];
}
```

**Array type:**

```php
/**
* @return array
*/
public function fields() : array
{
    return [
        'body' => [
            'tag'      => 'wysiwyg',
            'name'     => 'body',
            'max'      => 255,
            'required' => true,
            'rows'     => 10,
        ],
    ];
}
```

**Comment by Hrache** [comment]
... and how to add a single attribute such the **id** for **textarea** I used
**->set('id', 'markdowntextarea')**
but it draws own generated id
