### ISSUE TITLE
Typo in Code Example/Documentation (https://theorchid.github.io/en/docs/access/)

### ISSUE THREAD

**Issue by authanram** [TheOrchid/Platform#272]
### Expected Behavior
Auth::user()->hasAccess($string);

### Actual Behavior
Typo(s): Auth:user()->hasAccess($string);
Description: two colons (::) required instead of one.

### Steps to Reproduce the Problem

  1. Open: https://theorchid.github.io/en/docs/access/
  2. Scroll down to "User"
  3. Have a close look ;-)

### Specifications

  - None

![screen shot 2017-07-30 at 18 47 07](https://user-images.githubusercontent.com/1874088/28755312-16acef3c-7558-11e7-976b-8f9a4e62e99a.jpg)

**Comment by authanram** [comment]
+ the Namespace "Orchid\Foundation\..." you're using in a lot examples is not present. 

Hope this helps. ;-)

**Comment by tabuna** [comment]
Hello, thank you very much for bringing this to your attention.
Tell me there are any other points that may not be clear?

**Comment by tabuna** [comment]
I did not see the places where it was required to use namespace besides the Post models

![2017-07-30 20 27 58](https://user-images.githubusercontent.com/5102591/28755516-998ffdce-7565-11e7-8cbf-beaf0b2a651c.png)

**Comment by authanram** [comment]
Sure, you're Welcome. I really like your Work. Orchid ist awesome.

If it's okay i would fix some stuff and contribute it. At the points i'm
not deep enough in Orchid i will create an issue, if this will be okay for
you.

And as Inspiration, maybe you can have a Look to the fieldset Module from
Statamic, to create a CRUD right from the Dashboard. This would be freaking
awesome if it would be possible creating CRUDs without an IDE.

Cu! And Go Ahead... With that nice Thing! :-)
