### ISSUE TITLE
Error while resetting password

### ISSUE THREAD

**Issue by imranali1** [TheOrchid/Platform#274]
Error thrown while resting user password. 
Laravel Exception page shown.

### Steps to Reproduce the Problem

  1. Go to http://demo-orchid.tk/dashboard/password/reset
  2. Enter email: admin@admin.com
  3. Click Send Password Reset Link

**Comment by tabuna** [comment]
Thank you, we will fix this in the near future.

To solve this problem right now, issue the command
```
php artisan make:auth
````

**Comment by imranali1** [comment]
Thanks a lot 👍
