### ISSUE TITLE
Wanna use Post, but this menu not display

### ISSUE THREAD

**Issue by cloudsben** [TheOrchid/Platform#277]
### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - PHP Version: 7.1
  - Database Version:

![image](https://user-images.githubusercontent.com/1283779/28925810-88a11d46-7898-11e7-924f-afdcfc287b1c.png)

**Comment by tabuna** [comment]
Set permissions on record types:
![screencapture-demo-orchid-tk-dashboard-systems-users-50-edit-1501772141231 1](https://user-images.githubusercontent.com/5102591/28928124-1a3b3832-7875-11e7-9112-9770b9276624.png)

**Comment by cloudsben** [comment]
@tabuna Works for me ! Thanks a lot ! maybe you can record a video to youtube.
