### ISSUE TITLE
If use plus make me confuse. maybe can use check mark

### ISSUE THREAD

**Issue by cloudsben** [TheOrchid/Platform#278]
### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - PHP Version:
  - Database Version:

<img width="952" alt="default" src="https://user-images.githubusercontent.com/1283779/28930685-516bed16-78a6-11e7-88c6-2630fc2fedd1.png">

**Comment by tabuna** [comment]
I can not understand what change you are proposing?

**Comment by cloudsben** [comment]
I think when create template use icon-check -Save is better

**Comment by tabuna** [comment]
I changed it
