### ISSUE TITLE
Cache Index not using lang file

### ISSUE THREAD

**Issue by Benjyclay** [TheOrchid/Platform#284]
### Expected Behavior
Should be using @lang method instead of hard coded text

### Actual Behavior
Not using @lang

### Steps to Reproduce the Problem

  1. Go to /dashboard/systems/cache

Im happy to push this change but I don't know what they mean, so I'll leave them empty and someone can update them :)

**Comment by Benjyclay** [comment]
This only happens on the 0.0.28 release, and not on the most recent master branch because this page doesn't exist

**Comment by tabuna** [comment]
I confirm, I need to fix it

**Comment by tabuna** [comment]
dev-master fix
