### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by sharifzadesina** [TheOrchid/Platform#286]
Hi
Is there a way to bring RTL support to the orchid? for example by injecting CSS or JS to the dashboard?

**Comment by tabuna** [comment]
Hi, we are working on the possibility of adding css and js code. But there is no support for RTL in the plans

**Comment by sharifzadesina** [comment]
@tabuna, I know, it is ok, I will add it by myself if you provide the injection support.

**Comment by tabuna** [comment]
This is very pleasing to me, I suppose that such an opportunity will appear next week

**Comment by sharifzadesina** [comment]
@tabuna I don't know if you want continue this project alone or not :D but as I am really interested in this and I REALLY need it for my works, I can help you, what do you think? can you add me to the contributors?

**Comment by tabuna** [comment]
Let's talk in private [chat](https://join.slack.com/t/lara-orchid/shared_invite/MjIxODM3MDcxODcyLTE1MDE4NzY0MzctMzRiZTBlMzYxZg)

**Comment by tabuna** [comment]
In version 1.0 already exists, the ability to add your own scripts and styles globally

Example:
```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Orchid\Platform\Kernel\Dashboard;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(Dashboard $dashboard)
    {
        $dashboard->registerResource('stylesheets','custom.css');
        $dashboard->registerResource('scripts','custom.css');
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```
