### ISSUE TITLE
Admin role

### ISSUE THREAD

**Issue by sharifzadesina** [TheOrchid/Platform#289]
I think we need a pre-built admin role, so the admins can access to every thing and we do not need to change permissions for admins each time we are creating new post-type or new permission.

**Comment by VictorAvelar** [comment]
someone already on this?

**Comment by tabuna** [comment]
I do not think that partitions appear too often, you can create an administrator role and apply it to users.

**Comment by SmoDav** [comment]
There's a new `superuser` permission. If you assign a user this permission, he has all rights in the system.

**Comment by tabuna** [comment]
I still think this is not the best solution, since it will be difficult to get only users with a super role and this can confuse the first users
