### ISSUE TITLE
Wysiwyg editor

### ISSUE THREAD

**Issue by tabuna** [TheOrchid/Platform#300]
Tell me what wysiwyg editor would you like to see by default?
Write your suggestions, do not hesitate.

**Comment by dmitriymarley** [comment]
CKEditor :)

**Comment by oRastor** [comment]
SimpleMDE

**Comment by tabuna** [comment]
@oRastor If there is a markdown editor, then it will be necessary to set and parser

**Comment by wislem** [comment]
A mobile friendly one. Quilljs maybe? I love redactor, but that's a commercial product.

**Comment by tabuna** [comment]
@wislem I liked the Quilljs, but in the demo I did not see the benefits

**Comment by wislem** [comment]
> but in the demo I did not see the benefits
You mean mobile support? It's nothing fancy. It just plays as it should. It does not break the toolbar and stays within the viewport.

**Comment by wislem** [comment]
Actually, summernote is pretty nice too. I wouldn't change it. Although I would like to see copy+paste/drag 'n' drop image upload using the backend.

**Comment by tabuna** [comment]
I drew attention to [pell](https://github.com/jaredreich/pell)
