### ISSUE TITLE
CSS file not loaded on demo page

### ISSUE THREAD

**Issue by mtmail** [TheOrchid/Platform#304]
On https://demo.orchid.software/ the HTML points to

```
<link rel="stylesheet" href="http://demo.orchid.software/orchid/css/orchid.css" type="text/css"/>
<script async="async" src="http://demo.orchid.software/orchid/js/orchid.js" type="text/javascript"></script>
```

and the page looks broken in Firefox and Google Chrome.

![image](https://user-images.githubusercontent.com/3727288/29986979-35757196-8f66-11e7-8ad6-a06b3ea7e12f.png)

**Comment by tabuna** [comment]
Thank you for paying attention. I fixed this annoying error

**Comment by downtest** [comment]
> Thank you for paying attention. I fixed this annoying error

@tabuna, how have you fixed it? Please, always left the solution, if you have fixed it by yourself, because people could face with the same problem(like me now, all styles and scripts are not found by browser, it looks in /dashboard/resources/orchid/css/orchid.css)

**Comment by tabuna** [comment]
@downtest run command ‘artisan orchid:link’
