### ISSUE TITLE
Error on composer require orchid/platform:dev-master

### ISSUE THREAD

**Issue by Naoray** [TheOrchid/Platform#342]
### Expected Behavior
`composer require orchid/platform:dev-master` => adding all required packages to project.

### Actual Behavior
An error is thrown on `artisan package:discover`
![image](https://user-images.githubusercontent.com/10154100/33027436-5c31c62c-ce13-11e7-9080-563509c4ce37.png)

### Steps to Reproduce the Problem

  1. `laravel new project`
  2. `cd project`
  3. `composer require orchid/platform:dev-master`

### Specifications
  - PHP Version: 7.1
  - Database Version: 5.7.20

**Comment by tabuna** [comment]
Hey. I'm sorry that you came across this, the package is in development. 
Such a problem should no longer be.
